version: '3.9'
services: 
  mysql: 
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: airplaneSolutions
        MYSQL_USER: admin
        MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    